dataset:
  hf_dataset_id: Jackie2235/flickr30k_attn_ft

model:
  name: Qwen/Qwen3-VL-8B-Instruct
  trust_remote_code: true
  load_in_4bit: false
  lora_r: 8
  lora_alpha: 16
  lora_dropout: 0.1
  lora_target_modules: [q_proj, k_proj,v_proj, o_proj]
  attention_layers: 
    -2: 0.4
    -4: 0.2
    -6: 0.2
    -8: 0.2
  attention_heads: []

train:
  run_name: qwen3_vl_8B_attn_ft_bsz64_4l_allProj_suppress
  loss: suppress
  loss_weight: 4
  seed: 42
  micro_batch_size: 16
  effective_batch_size: 64
  num_epochs: 1
  lr: 1.0e-5
  weight_decay: 0.01
  warmup_steps: 100
  mixed_precision: bf16
  log_every: 10
  save_every: 500
  wandb_enabled: true
  wandb_project: attn_ft
