dataset:
  hf_dataset_id: Jackie2235/flickr30k_attn_ft

model:
  name: Qwen/Qwen3-VL-2B-Instruct
  trust_remote_code: true
  load_in_4bit: false
  lora_r: 32
  lora_alpha: 64
  lora_dropout: 0.1
  lora_target_modules: [q_proj, k_proj]
  attention_layers: 
    -2: 0.4
    -4: 0.2
    -6: 0.2
    -8: 0.2
  attention_heads: []

train:
  run_name: qwen3_vl_2B_attn_ft_bsz64_4l_suppress
  loss: suppress
  loss_weight: 2
  seed: 42
  micro_batch_size: 32
  effective_batch_size: 64
  num_epochs: 1
  lr: 1.0e-4
  weight_decay: 0.1
  warmup_steps: 200
  mixed_precision: bf16
  log_every: 20
  save_every: 1000
  wandb_enabled: true
  wandb_project: attn_ft
